credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: "$2b$12$e./8.VFpf60wR1jGhsJ3WOMi5RqE6UqGZl3FkjBoWJtSAOVDVRCxK"  # Hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: "$2b$12$MvKlIs9DP3AGSPQJZpQZiOavS1b62lR0kG/BQgqK9BygWwi3hTgE2"  # Hashed password
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
